### ISSUE TITLE
Wake lock not active in multiphase 

### ISSUE THREAD

**Issue by vgammieri** [CubeStuffs/CubeTime#39]
In multiphase session the screen turns off while solving the cube (I’m very slow, F2L take more than 1m)

1. Create a multiphase session 
2. Start the timer
3. Wait the system screen timeout 
4. The screen turn off and the device locks

**Expected behavior**
Screen should remain active 

 - Device: iPhone8
 - OS: iOS15.3
 - App version 1.1

**Comment by Wardeneo** [comment]
I am also having same issue when in second/third/fourth phases of my multiphase session (I have 4 stages to time cross, F2L, OLL and PLL and I too am quite slow learning new algorithms so my screen times out too)

device - iPhone 13 pro max 512gb
OS: iOS 15.3
App version 1.1

**Comment by pdtxie** [comment]
fixed in version 1.2 to be released

**Comment by vgammieri** [comment]
Sorry but my iPhone still locks the screen after few minutes and tuner running! Issue is not solved

**Comment by vgammieri** [comment]
If you want I can test a TestFlight version to check if problem is solved on my iPhone.

**Comment by pdtxie** [comment]
@vgammieri I have had another look, and have made some changes. The issue should be fixed. The build is being processed on Testflight: https://testflight.apple.com/join/yQw9o9rb
Thank you!

**Comment by vgammieri** [comment]
Just tried the TestFlight build and after abiut  1,5min my iPhone still lock !!!!! Sorry

Inviato da iPhone

**Comment by pdtxie** [comment]
The new testflight build hasn't been processed yet. The current testflight build is still the old one. Sorry!! Might need to wait some time for Apple to process it.

**Comment by xbjfk** [comment]
I'll close this for now, and I will reopen it if the issue is still present, our testing shows it is fixed.

**Comment by pdtxie** [comment]
Testflight build has been processed. If the issue is still present, reopen this issue. Thanks
